/* Code generated by AI (GitHub Copilot) */

import React from 'react';
import './ArticleCounter.css';

interface ArticleCounterProps {
  visibleCount: number;
  totalCount: number;
}

export const ArticleCounter: React.FC<ArticleCounterProps> = ({ visibleCount, totalCount }) => {
  return (
    <div className="article-counter">
      {visibleCount}/{totalCount}
    </div>
  );
};
