/* Code generated by AI (Claude 3.5 Sonnet) */

import React from 'react';
import type { Article } from '../../types/Article';
import { BookmarkService } from '../../services/BookmarkService';
import './BookmarkButton.css';

interface BookmarkButtonProps {
    article: Article;
    onBookmarkChange?: () => void;
}

export const BookmarkButton: React.FC<BookmarkButtonProps> = ({ article, onBookmarkChange }) => {
    const [isBookmarked, setIsBookmarked] = React.useState(() => 
        BookmarkService.isBookmarked(article)
    );

    const toggleBookmark = (e: React.MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        
        if (isBookmarked) {
            BookmarkService.removeBookmark(article);
        } else {
            BookmarkService.addBookmark(article);
        }
        
        setIsBookmarked(!isBookmarked);
        onBookmarkChange?.();
    };

    return (
        <button 
            className={`bookmark-button ${isBookmarked ? 'active' : ''}`}
            onClick={toggleBookmark}
            title={isBookmarked ? 'Remove from bookmarks' : 'Add to bookmarks'}
        >
            {isBookmarked ? (
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M17 3H7c-1.1 0-2 .9-2 2v16l7-3 7 3V5c0-1.1-.9-2-2-2z"/>
                </svg>
            ) : (
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                    <path d="M17 3H7c-1.1 0-2 .9-2 2v16l7-3 7 3V5c0-1.1-.9-2-2-2zm0 15l-5-2.18L7 18V5h10v13z"/>
                </svg>
            )}
        </button>
    );
};
