/* Code generated by AI (Claude 3.5 Sonnet) */

export interface ArticleSourceConfig {
  name: string;
  category: string;
  baseUrl: string;
  dateFormat?: string;
  corsProxy?: string | null;
  selectors: {
    container: string;
    title: string;
    description: string;
    image: string;
    date: string;
    link: string;
  };
  transformers?: {
    articleUrl?: string;
    imageUrl?: string;
  };
}

