/* Code generated by AI (Claude 3.5 Sonnet) */

type Article = {
  id: string;
  title: string;
  date: string;
  description: string;
  imageUrl: string;
  articleUrl: string;
  sourceName: string;
  category: string;
};

export type { Article };
