/* Code generated by AI (Claude 3.5 Sonnet) */

import { useState, useEffect } from 'react';
import { ProgressBar } from '../ProgressBar/ProgressBar';
import './LoadingProgressBars.css';

export interface SourceLoadingStatus {
  name: string;
  isLoading: boolean;
  progress: number;
  hasError: boolean;
  errorMessage?: string;
}

interface LoadingProgressBarsProps {
  sources: SourceLoadingStatus[];
}

export const LoadingProgressBars: React.FC<LoadingProgressBarsProps> = ({ sources }) => {
  const isAnySourceLoading = sources.some(source => source.isLoading);
  const hasErrors = sources.some(source => source.hasError);
  
  const [isVisible, setIsVisible] = useState(true);
  const [isHiding, setIsHiding] = useState(false);
  
  useEffect(() => {
    if (!isAnySourceLoading) {
      // Set different hide delays depending on whether there are errors
      const hideDelay = hasErrors ? 5000 : 2000; // 5 seconds for errors, 2 seconds for success
      
      // Start fade-out animation
      setIsHiding(true);
      
      // Hide component after animation
      const timer = setTimeout(() => {
        setIsVisible(false);
      }, hideDelay);
      
      return () => clearTimeout(timer);
    } else {
      setIsHiding(false);
      setIsVisible(true);
    }
  }, [isAnySourceLoading, hasErrors]);

  // Show again when new loading starts
  useEffect(() => {
    if (isAnySourceLoading) {
      setIsVisible(true);
      setIsHiding(false);
    }
  }, [isAnySourceLoading]);

  if (!isVisible) return null;

  return (
    <div className={`loading-progress-bars ${isHiding ? 'hiding' : ''}`}>
      {sources.map(source => {
        const label = source.hasError 
          ? `${source.name} - ${source.errorMessage || 'Error loading articles'}`
          : source.isLoading 
            ? `${source.name} - Loading articles...`
            : `${source.name} - Completed`;

        return (
          <ProgressBar
            key={source.name}
            isVisible={true}
            label={label}
            progress={source.progress}
            hasError={source.hasError}
          />
        );
      })}
    </div>
  );
};
